In [1]:
import numpy as np
import pandas as pd

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
df = pd.read_excel("Online Retail.xlsx")

print("Dataset loaded successfully!")
print("Shape:", df.shape)

display(df.head())

Dataset loaded successfully!
Shape: (541909, 8)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [3]:
print("First five rows:")
display(df.head())

print("\nDataset dimensions:")
print(df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nDataset information:")
df.info()

print("\nMissing values in each column:")
print(df.isnull().sum())

First five rows:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

Dataset dimensions:
(541909, 8)

Column names:
['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

Missing values in each column:
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [4]:
df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce")
df["UnitPrice"] = pd.to_numeric(df["UnitPrice"], errors="coerce")

df["InvoiceDate"] = pd.to_datetime(
    df["InvoiceDate"],
    errors="coerce"
)

df["Revenue"] = df["Quantity"] * df["UnitPrice"]

print("Revenue column created successfully.")

display(
    df[
        [
            "InvoiceNo",
            "Description",
            "Quantity",
            "UnitPrice",
            "Revenue"
        ]
    ].head()
)

Revenue column created successfully.

  InvoiceNo                          Description  Quantity  UnitPrice  Revenue
0    536365   WHITE HANGING HEART T-LIGHT HOLDER         6       2.55    15.30
1    536365                  WHITE METAL LANTERN         6       3.39    20.34
2    536365       CREAM CUPID HEARTS COAT HANGER         8       2.75    22.00
3    536365  KNITTED UNION FLAG HOT WATER BOTTLE         6       3.39    20.34
4    536365       RED WOOLLY HOTTIE WHITE HEART.         6       3.39    20.34

In [5]:
revenue_array = df["Revenue"].dropna().to_numpy()

print("First 10 revenue values:")
print(revenue_array[:10])

print("\nFirst revenue value:")
print(revenue_array[0])

print("\nRevenue values from index 0 to 9:")
print(revenue_array[0:10])

First 10 revenue values:
[15.3  20.34 22.   20.34 20.34 15.3  25.5  11.1  11.1  54.08]

First revenue value:
15.299999999999999

Revenue values from index 0 to 9:
[15.3  20.34 22.   20.34 20.34 15.3  25.5  11.1  11.1  54.08]

In [6]:
quantity_array = df["Quantity"].dropna().to_numpy()

print("First 10 quantities:")
print(quantity_array[:10])

print("\nFirst 10 quantities increased by 1:")
print(quantity_array[:10] + 1)

print("\nSmallest 10 quantities:")
print(np.sort(quantity_array)[:10])

First 10 quantities:
[ 6  6  8  6  6  2  6  6  6 32]

First 10 quantities increased by 1:
[ 7  7  9  7  7  3  7  7  7 33]

Smallest 10 quantities:
[-80995 -74215  -9600  -9600  -9360  -9058  -5368  -4830  -3667  -3167]

In [7]:
print("Total revenue:", np.sum(revenue_array))
print("Average revenue per transaction line:", np.mean(revenue_array))
print("Median revenue:", np.median(revenue_array))
print("Minimum revenue:", np.min(revenue_array))
print("Maximum revenue:", np.max(revenue_array))
print("Standard deviation:", np.std(revenue_array))

Total revenue: 9747747.934
Average revenue per transaction line: 17.987794876999644
Median revenue: 9.75
Minimum revenue: -168469.6
Maximum revenue: 168469.6
Standard deviation: 378.8104739906518

In [8]:
description_series = df["Description"]

print("Product descriptions:")
display(description_series.head())

Product descriptions:

0     WHITE HANGING HEART T-LIGHT HOLDER
1                    WHITE METAL LANTERN
2         CREAM CUPID HEARTS COAT HANGER
3    KNITTED UNION FLAG HOT WATER BOTTLE
4         RED WOOLLY HOTTIE WHITE HEART.
Name: Description, dtype: object

In [9]:
selected_data = df[
    [
        "Description",
        "Quantity",
        "UnitPrice",
        "Revenue"
    ]
]

display(selected_data.head())

                           Description  Quantity  UnitPrice  Revenue
0   WHITE HANGING HEART T-LIGHT HOLDER         6       2.55    15.30
1                  WHITE METAL LANTERN         6       3.39    20.34
2       CREAM CUPID HEARTS COAT HANGER         8       2.75    22.00
3  KNITTED UNION FLAG HOT WATER BOTTLE         6       3.39    20.34
4       RED WOOLLY HOTTIE WHITE HEART.         6       3.39    20.34

In [10]:
high_revenue = df[df["Revenue"] > 500]

print("Transaction lines with revenue above £500:")
display(high_revenue.head())

print("Number of matching rows:", len(high_revenue))

Transaction lines with revenue above £500:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
178,536387,79321,CHILLI LIGHTS,192,2010-12-01 09:58:00,3.82,16029.0,United Kingdom,733.44
179,536387,22780,LIGHT GARLAND BUTTERFILES PINK,192,2010-12-01 09:58:00,3.37,16029.0,United Kingdom,647.04
180,536387,22779,WOODEN OWLS LIGHT GARLAND,192,2010-12-01 09:58:00,3.37,16029.0,United Kingdom,647.04
181,536387,22466,FAIRY TALE COTTAGE NIGHTLIGHT,432,2010-12-01 09:58:00,1.45,16029.0,United Kingdom,626.40
182,536387,21731,RED TOADSTOOL LED NIGHT LIGHT,432,2010-12-01 09:58:00,1.25,16029.0,United Kingdom,540.00

Number of matching rows: 1155

In [11]:
print("Missing values before handling:")
print(df.isnull().sum())

Missing values before handling:
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
Revenue             0
dtype: int64

In [12]:
df["Description"] = df["Description"].fillna("Unknown Product")

df["Country"] = df["Country"].fillna("Unknown Country")

print("Missing values after handling selected columns:")
print(df[["Description", "Country"]].isnull().sum())

Missing values after handling selected columns:
Description    0
Country        0
dtype: int64

In [13]:
df = df.dropna(
    subset=["Quantity", "UnitPrice", "InvoiceDate"]
)

df["Revenue"] = df["Quantity"] * df["UnitPrice"]

print("Missing values in essential columns:")
print(df[["Quantity", "UnitPrice", "InvoiceDate"]].isnull().sum())

Missing values in essential columns:
Quantity       0
UnitPrice      0
InvoiceDate    0
dtype: int64

In [14]:
df["Description"] = df["Description"].str.strip()

display(df["Description"].head())

0     WHITE HANGING HEART T-LIGHT HOLDER
1                    WHITE METAL LANTERN
2         CREAM CUPID HEARTS COAT HANGER
3    KNITTED UNION FLAG HOT WATER BOTTLE
4         RED WOOLLY HOTTIE WHITE HEART.
Name: Description, dtype: object

In [15]:
df["Description"] = df["Description"].str.upper()

display(df["Description"].head())

0     WHITE HANGING HEART T-LIGHT HOLDER
1                    WHITE METAL LANTERN
2         CREAM CUPID HEARTS COAT HANGER
3    KNITTED UNION FLAG HOT WATER BOTTLE
4         RED WOOLLY HOTTIE WHITE HEART.
Name: Description, dtype: object

In [16]:
heart_products = df[
    df["Description"].str.contains(
        "HEART",
        na=False
    )
]

print("Products containing 'HEART':")
display(heart_products[["StockCode", "Description"]].head(10))

Products containing 'HEART':

   StockCode                         Description
0     85123A  WHITE HANGING HEART T-LIGHT HOLDER
2     84406B      CREAM CUPID HEARTS COAT HANGER
4     84029E      RED WOOLLY HOTTIE WHITE HEART.
19     21777         RECIPE BOX WITH METAL HEART
49    85123A  WHITE HANGING HEART T-LIGHT HOLDER
51    84406B      CREAM CUPID HEARTS COAT HANGER
62    84029E      RED WOOLLY HOTTIE WHITE HEART.
66    85123A  WHITE HANGING HEART T-LIGHT HOLDER
68    84406B      CREAM CUPID HEARTS COAT HANGER
79    84029E      RED WOOLLY HOTTIE WHITE HEART.

In [17]:
df["InvoiceDate"] = pd.to_datetime(
    df["InvoiceDate"],
    errors="coerce"
)

df["Year"] = df["InvoiceDate"].dt.year
df["Month"] = df["InvoiceDate"].dt.month
df["Day"] = df["InvoiceDate"].dt.day
df["Weekday"] = df["InvoiceDate"].dt.day_name()

display(
    df[
        [
            "InvoiceDate",
            "Year",
            "Month",
            "Day",
            "Weekday"
        ]
    ].head()
)

          InvoiceDate  Year  Month  Day    Weekday
0 2010-12-01 08:26:00  2010     12    1  Wednesday
1 2010-12-01 08:26:00  2010     12    1  Wednesday
2 2010-12-01 08:26:00  2010     12    1  Wednesday
3 2010-12-01 08:26:00  2010     12    1  Wednesday
4 2010-12-01 08:26:00  2010     12    1  Wednesday

In [18]:
country_summary = df.groupby("Country").agg(
    Total_Revenue=("Revenue", "sum"),
    Average_Revenue=("Revenue", "mean"),
    Total_Quantity=("Quantity", "sum"),
    Unique_Invoices=("InvoiceNo", "nunique"),
    Transaction_Lines=("InvoiceNo", "count")
)

country_summary = country_summary.sort_values(
    by="Total_Revenue",
    ascending=False
)

print("Country-wise retail analysis:")
display(country_summary.head(15))

Country-wise retail analysis:

,Total_Revenue,Average_Revenue,Total_Quantity,Unique_Invoices,Transaction_Lines
Country,,,,,
United Kingdom,8187806.364,16.525065,4263829,23494,495478
Netherlands,284661.540,120.059696,200128,101,2371
EIRE,263276.820,32.122599,142637,360,8196
Germany,221698.210,23.348943,117448,603,9495
France,197403.900,23.069288,110480,461,8557
Australia,137077.270,108.877895,83653,69,1259
Switzerland,56385.350,28.164510,30325,74,2002
Spain,54774.580,21.624390,26824,105,2533
Belgium,40910.960,19.773301,23152,119,2069
Sweden,36595.910,79.211926,35637,46,462
Japan,35340.620,98.716816,25218,28,358
Norway,35163.460,32.378877,19247,40,1086
Portugal,29367.020,19.333127,16180,71,1519
Finland,22326.740,32.124806,10666,48,695
Channel Islands,20086.290,26.499063,9479,33,758

In [19]:
country_year_revenue = df.groupby(
    ["Country", "Year"]
)["Revenue"].sum()

print("Revenue by country and year:")
display(country_year_revenue.head(10))

first_country = country_year_revenue.index.get_level_values(
    "Country"
)[0]

print("\nYear-wise revenue for", first_country)
display(country_year_revenue.loc[first_country])

Revenue by country and year:

Country    Year
Australia  2010      1005.10
           2011    136072.17
Austria    2010       257.04
           2011      9897.28
Bahrain    2010       205.74
           2011       342.66
Belgium    2010      1809.91
           2011     39101.05
Brazil     2011      1143.60
Canada     2011      3666.38
Name: Revenue, dtype: float64

Year-wise revenue for Australia

Year
2010      1005.10
2011    136072.17
Name: Revenue, dtype: float64

In [20]:
pivot_table = pd.pivot_table(
    df,
    values="Revenue",
    index="Country",
    columns="Year",
    aggfunc="sum",
    fill_value=0
)

print("Country-wise revenue by year:")
display(pivot_table.head(15))

Country-wise revenue by year:

Year                    2010       2011
Country
Australia            1005.10  136072.17
Austria               257.04    9897.28
Bahrain               205.74     342.66
Belgium              1809.91   39101.05
Brazil                  0.00    1143.60
Canada                  0.00    3666.38
Channel Islands       363.53   19722.76
Cyprus               1590.82   11355.47
Czech Republic          0.00     707.72
Denmark              1281.50   17486.64
EIRE                 9029.95  254246.87
European Community      0.00    1291.75
Finland               892.80   21433.94
France               9575.36  187828.54
Germany             14562.84  207135.37

In [21]:
high_value_transactions = df.query("Revenue > 500")

print("Transactions with revenue above £500:")
display(
    high_value_transactions[
        [
            "InvoiceNo",
            "Description",
            "Quantity",
            "UnitPrice",
            "Revenue"
        ]
    ].head(10)
)

Transactions with revenue above £500:

     InvoiceNo                      Description  Quantity  UnitPrice  Revenue
178     536387                    CHILLI LIGHTS       192       3.82   733.44
179     536387   LIGHT GARLAND BUTTERFILES PINK       192       3.37   647.04
180     536387        WOODEN OWLS LIGHT GARLAND       192       3.37   647.04
181     536387    FAIRY TALE COTTAGE NIGHTLIGHT       432       1.45   626.40
182     536387    RED TOADSTOOL LED NIGHT LIGHT       432       1.25   540.00
870     536477         BLACK RECORD COVER FRAME       480       3.39  1627.20
1576    536544         REGENCY CAKESTAND 3 TIER        40      12.72   508.80
1814    536544                   DOTCOM POSTAGE         1     569.77   569.77
2316    536576  SET OF 3 COLOURED  FLYING DUCKS       120       4.65   558.00
2364    536584   RED WOOLLY HOTTIE WHITE HEART.       384       2.95  1132.80

In [22]:
calculated_revenue = df.eval("Quantity * UnitPrice")

print("Revenue calculated using eval():")
display(calculated_revenue.head(10))

Revenue calculated using eval():

0    15.30
1    20.34
2    22.00
3    20.34
4    20.34
5    15.30
6    25.50
7    11.10
8    11.10
9    54.08
dtype: float64

In [23]:
print(
    "Revenue calculations match:",
    np.allclose(
        df["Revenue"].to_numpy(),
        calculated_revenue.to_numpy(),
        equal_nan=True
    )
)

Revenue calculations match: True

In [24]:
print("Descriptive statistics:")
display(
    df[
        [
            "Quantity",
            "UnitPrice",
            "Revenue"
        ]
    ].describe()
)

Descriptive statistics:

            Quantity      UnitPrice        Revenue
count  541909.000000  541909.000000  541909.000000
mean        9.552250       4.611114      17.987795
std       218.081158      96.759853     378.810824
min    -80995.000000  -11062.060000 -168469.600000
25%         1.000000       1.250000       3.400000
50%         3.000000       2.080000       9.750000
75%        10.000000       4.130000      17.400000
max     80995.000000   38970.000000  168469.600000

In [25]:
top_countries = country_summary.sort_values(
    by="Total_Revenue",
    ascending=False
).head(10)

print("Top 10 countries by total revenue:")
display(top_countries)

Top 10 countries by total revenue:

,Total_Revenue,Average_Revenue,Total_Quantity,Unique_Invoices,Transaction_Lines
Country,,,,,
United Kingdom,8187806.364,16.525065,4263829,23494,495478
Netherlands,284661.540,120.059696,200128,101,2371
EIRE,263276.820,32.122599,142637,360,8196
Germany,221698.210,23.348943,117448,603,9495
France,197403.900,23.069288,110480,461,8557
Australia,137077.270,108.877895,83653,69,1259
Switzerland,56385.350,28.164510,30325,74,2002
Spain,54774.580,21.624390,26824,105,2533
Belgium,40910.960,19.773301,23152,119,2069
Sweden,36595.910,79.211926,35637,46,462

In [26]:
top_transactions = df.sort_values(
    by="Revenue",
    ascending=False
).head(10)

print("Top 10 transaction lines by revenue:")
display(
    top_transactions[
        [
            "InvoiceNo",
            "Description",
            "Quantity",
            "UnitPrice",
            "Revenue",
            "Country"
        ]
    ]
)

Top 10 transaction lines by revenue:

,InvoiceNo,Description,Quantity,UnitPrice,Revenue,Country
540421,581483,"PAPER CRAFT , LITTLE BIRDIE",80995,2.08,168469.60,United Kingdom
61619,541431,MEDIUM CERAMIC TOP STORAGE JAR,74215,1.04,77183.60,United Kingdom
222680,556444,PICNIC BASKET WICKER 60 PIECES,60,649.50,38970.00,United Kingdom
15017,537632,AMAZON FEE,1,13541.33,13541.33,United Kingdom
299982,A563185,ADJUST BAD DEBT,1,11062.06,11062.06,United Kingdom
173382,551697,POSTAGE,1,8142.75,8142.75,United Kingdom
348325,567423,SET OF TEA COFFEE SUGAR TINS PANTRY,1412,5.06,7144.72,United Kingdom
52711,540815,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,2.10,6539.40,United Kingdom
160546,550461,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,2.10,6539.40,United Kingdom
421601,573003,RABBIT NIGHT LIGHT,2400,2.08,4992.00,Netherlands

In [27]:
print("Final dataset dimensions:")
print(df.shape)

print("\nFinal column names:")
print(df.columns.tolist())

print("\nMissing values in each column:")
print(df.isnull().sum())

print("\nFirst five records:")
display(df.head())

Final dataset dimensions:
(541909, 13)

Final column names:
['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country', 'Revenue', 'Year', 'Month', 'Day', 'Weekday']

Missing values in each column:
InvoiceNo           0
StockCode           0
Description         1
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
Revenue             0
Year                0
Month               0
Day                 0
Weekday             0
dtype: int64

First five records:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,Year,Month,Day,Weekday
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,2010,12,1,Wednesday
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010,12,1,Wednesday
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,2010,12,1,Wednesday
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010,12,1,Wednesday
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010,12,1,Wednesday